//<![CDATA[
/* Modernizr 2.7.1 (Custom Build) | MIT & BSD
 * Build: http://modernizr.com/download/#-fontface-backgroundsize-borderimage-borderradius-boxshadow-flexbox-flexboxlegacy-hsla-multiplebgs-opacity-rgba-textshadow-cssanimations-csscolumns-generatedcontent-cssgradients-cssreflections-csstransforms-csstransforms3d-csstransitions-applicationcache-canvas-canvastext-draganddrop-hashchange-history-audio-video-indexeddb-input-inputtypes-localstorage-postmessage-sessionstorage-websockets-websqldatabase-webworkers-geolocation-inlinesvg-smil-svg-svgclippaths-touch-webgl-shiv-cssclasses-teststyles-testprop-testallprops-hasevent-prefixes-domprefixes-load
 */
window.Modernizr=function(g,d,y){function u(a,b){return typeof a===b}function B(a,b){for(var e in a){var s=a[e];if(!~(""+s).indexOf("-")&&m[s]!==y)return"pfx"==b?s:!0}return!1}function p(a,b,e){var s=a.charAt(0).toUpperCase()+a.slice(1),c=(a+" "+C.join(s+" ")+s).split(" ");if(u(b,"string")||u(b,"undefined"))b=B(c,b);else a:{c=(a+" "+D.join(s+" ")+s).split(" "),a=c;for(var d in a)if(s=b[a[d]],s!==y){b=!1===e?a[d]:u(s,"function")?s.bind(e||b):s;break a}b=!1}return b}function O(){f.input=function(a){for(var b=
0,e=a.length;b<e;b++)E[a[b]]=a[b]in k;return E.list&&(E.list=!!d.createElement("datalist")&&!!g.HTMLDataListElement),E}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));f.inputtypes=function(a){for(var b=0,e,s,c,f=a.length;b<f;b++)k.setAttribute("type",s=a[b]),(e="text"!==k.type)&&(k.value=w,k.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(s)&&k.style.WebkitAppearance!==y?(v.appendChild(k),c=d.defaultView,e=c.getComputedStyle&&"textfield"!==
c.getComputedStyle(k,null).WebkitAppearance&&0!==k.offsetHeight,v.removeChild(k)):/^(search|tel)$/.test(s)||(/^(url|email)$/.test(s)?e=k.checkValidity&&!1===k.checkValidity():e=k.value!=w)),N[a[b]]=!!e;return N}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var f={},v=d.documentElement,c=d.createElement("modernizr"),m=c.style,k=d.createElement("input"),w=":)",x={}.toString,z=" -webkit- -moz- -o- -ms- ".split(" "),C=["Webkit","Moz","O","ms"],D=["webkit",
"moz","o","ms"],c={},N={},E={},G=[],H=G.slice,I,A=function(a,b,e,c){var f,k,g,l,r=d.createElement("div"),n=d.body,t=n||d.createElement("body");if(parseInt(e,10))for(;e--;)g=d.createElement("div"),g.id=c?c[e]:"modernizr"+(e+1),r.appendChild(g);return f=['&#173;<style id="smodernizr">',a,"</style>"].join(""),r.id="modernizr",(n?r:t).innerHTML+=f,t.appendChild(r),n||(t.style.background="",t.style.overflow="hidden",l=v.style.overflow,v.style.overflow="hidden",v.appendChild(t)),k=b(r,a),n?r.parentNode.removeChild(r):
(t.parentNode.removeChild(t),v.style.overflow=l),!!k},J=function(){var a={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(b,e){e=e||d.createElement(a[b]||"div");b="on"+b;var c=b in e;return c||(e.setAttribute||(e=d.createElement("div")),e.setAttribute&&e.removeAttribute&&(e.setAttribute(b,""),c=u(e[b],"function"),u(e[b],"undefined")||(e[b]=y),e.removeAttribute(b))),c}}(),q={}.hasOwnProperty,F;u(q,"undefined")||u(q.call,"undefined")?F=function(a,
b){return b in a&&u(a.constructor.prototype[b],"undefined")}:F=function(a,b){return q.call(a,b)};Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError;var e=H.call(arguments,1),c=function(){if(this instanceof c){var d=function(){};d.prototype=b.prototype;var d=new d,f=b.apply(d,e.concat(H.call(arguments)));return Object(f)===f?f:d}return b.apply(a,e.concat(H.call(arguments)))};return c});c.flexbox=function(){return p("flexWrap")};c.flexboxlegacy=
function(){return p("boxDirection")};c.canvas=function(){var a=d.createElement("canvas");return!!a.getContext&&!!a.getContext("2d")};c.canvastext=function(){return!!f.canvas&&!!u(d.createElement("canvas").getContext("2d").fillText,"function")};c.webgl=function(){return!!g.WebGLRenderingContext};c.touch=function(){var a;return"ontouchstart"in g||g.DocumentTouch&&d instanceof DocumentTouch?a=!0:A(["@media (",z.join("touch-enabled),("),"modernizr){#modernizr{top:9px;position:absolute}}"].join(""),function(b){a=
9===b.offsetTop}),a};c.geolocation=function(){return"geolocation"in navigator};c.postmessage=function(){return!!g.postMessage};c.websqldatabase=function(){return!!g.openDatabase};c.indexedDB=function(){return!!p("indexedDB",g)};c.hashchange=function(){return J("hashchange",g)&&(d.documentMode===y||7<d.documentMode)};c.history=function(){return!!g.history&&!!history.pushState};c.draganddrop=function(){var a=d.createElement("div");return"draggable"in a||"ondragstart"in a&&"ondrop"in a};c.websockets=
function(){return"WebSocket"in g||"MozWebSocket"in g};c.rgba=function(){m.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+m.backgroundColor).indexOf("rgba")};c.hsla=function(){m.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+m.backgroundColor).indexOf("rgba")||!!~(""+m.backgroundColor).indexOf("hsla")};c.multiplebgs=function(){m.cssText="background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(m.background)};c.backgroundsize=function(){return p("backgroundSize")};
c.borderimage=function(){return p("borderImage")};c.borderradius=function(){return p("borderRadius")};c.boxshadow=function(){return p("boxShadow")};c.textshadow=function(){return""===d.createElement("div").style.textShadow};c.opacity=function(){var a=z.join("opacity:.55;")+"";m.cssText=a;return/^0.55$/.test(m.opacity)};c.cssanimations=function(){return p("animationName")};c.csscolumns=function(){return p("columnCount")};c.cssgradients=function(){var a=("background-image:-webkit-gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:"+
z.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);m.cssText=a;return!!~(""+m.backgroundImage).indexOf("gradient")};c.cssreflections=function(){return p("boxReflect")};c.csstransforms=function(){return!!p("transform")};c.csstransforms3d=function(){var a=!!p("perspective");return a&&"webkitPerspective"in v.style&&A("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",function(b,e){a=9===b.offsetLeft&&3===b.offsetHeight}),a};
c.csstransitions=function(){return p("transition")};c.fontface=function(){var a;return A('@font-face {font-family:"font";src:url("https://")}',function(b,e){var c=d.getElementById("smodernizr"),c=(c=c.sheet||c.styleSheet)?c.cssRules&&c.cssRules[0]?c.cssRules[0].cssText:c.cssText||"":"";a=/src/i.test(c)&&0===c.indexOf(e.split(" ")[0])}),a};c.generatedcontent=function(){var a;return A(['#modernizr{font:0/0 a}#modernizr:after{content:"',w,'";visibility:hidden;font:3px/1 a}'].join(""),function(b){a=3<=
b.offsetHeight}),a};c.video=function(){var a=d.createElement("video"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,"")}catch(c){}return b};c.audio=function(){var a=d.createElement("audio"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,
""),b.mp3=a.canPlayType("audio/mpeg;").replace(/^no$/,""),b.wav=a.canPlayType('audio/wav; codecs="1"').replace(/^no$/,""),b.m4a=(a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")).replace(/^no$/,"")}catch(c){}return b};c.localstorage=function(){try{return localStorage.setItem("modernizr","modernizr"),localStorage.removeItem("modernizr"),!0}catch(a){return!1}};c.sessionstorage=function(){try{return sessionStorage.setItem("modernizr","modernizr"),sessionStorage.removeItem("modernizr"),!0}catch(a){return!1}};
c.webworkers=function(){return!!g.Worker};c.applicationcache=function(){return!!g.applicationCache};c.svg=function(){return!!d.createElementNS&&!!d.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};c.inlinesvg=function(){var a=d.createElement("div");return a.innerHTML="<svg/>","http://www.w3.org/2000/svg"==(a.firstChild&&a.firstChild.namespaceURI)};c.smil=function(){return!!d.createElementNS&&/SVGAnimate/.test(x.call(d.createElementNS("http://www.w3.org/2000/svg","animate")))};c.svgclippaths=
function(){return!!d.createElementNS&&/SVGClipPath/.test(x.call(d.createElementNS("http://www.w3.org/2000/svg","clipPath")))};for(var K in c)F(c,K)&&(I=K.toLowerCase(),f[I]=c[K](),G.push((f[I]?"":"no-")+I));f.input||O();f.addTest=function(a,b){if("object"==typeof a)for(var c in a)F(a,c)&&f.addTest(c,a[c]);else{a=a.toLowerCase();if(f[a]!==y)return f;b="function"==typeof b?b():b;v.className+=" "+(b?"":"no-")+a;f[a]=b}return f};m.cssText="";return c=k=null,function(a,b){function c(){var b=m.elements;
return"string"==typeof b?b.split(" "):b}function d(b){var a=h[b[p]];return a||(a={},L++,b[p]=L,h[L]=a),a}function f(a,c,e){c||(c=b);if(M)return c.createElement(a);e||(e=d(c));var h;return e.cache[a]?h=e.cache[a].cloneNode():n.test(a)?h=(e.cache[a]=e.createElem(a)).cloneNode():h=e.createElem(a),!h.canHaveChildren||r.test(a)||h.tagUrn?h:e.frag.appendChild(h)}function g(b,a){a.cache||(a.cache={},a.createElem=b.createElement,a.createFrag=b.createDocumentFragment,a.frag=a.createFrag());b.createElement=
function(c){return m.shivMethods?f(c,b,a):a.createElem(c)};b.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+c().join().replace(/[\w\-]+/g,function(b){return a.createElem(b),a.frag.createElement(b),'c("'+b+'")'})+");return n}")(m,a.frag)}function k(a){a||(a=b);var c=d(a);if(m.shivCSS&&!t&&!c.hasCSS){var e,h=a;e=h.createElement("p");h=h.getElementsByTagName("head")[0]||h.documentElement;e=(e.innerHTML="x<style>article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}mark{background:#FF0;color:#000}template{display:none}</style>",
h.insertBefore(e.lastChild,h.firstChild));c.hasCSS=!!e}return M||g(a,c),a}var l=a.html5||{},r=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,n=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,t,p="_html5shiv",L=0,h={},M;(function(){try{var a=b.createElement("a");a.innerHTML="<xyz></xyz>";t="hidden"in a;var c;if(!(c=1==a.childNodes.length)){b.createElement("a");var e=b.createDocumentFragment();c="undefined"==typeof e.cloneNode||
"undefined"==typeof e.createDocumentFragment||"undefined"==typeof e.createElement}M=c}catch(d){M=t=!0}})();var m={elements:l.elements||"abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output progress section summary template time video",version:"3.7.0",shivCSS:!1!==l.shivCSS,supportsUnknownElements:M,shivMethods:!1!==l.shivMethods,type:"default",shivDocument:k,createElement:f,createDocumentFragment:function(a,h){a||(a=b);
if(M)return a.createDocumentFragment();h=h||d(a);for(var n=h.frag.cloneNode(),f=0,r=c(),t=r.length;f<t;f++)n.createElement(r[f]);return n}};a.html5=m;k(b)}(this,d),f._version="2.7.1",f._prefixes=z,f._domPrefixes=D,f._cssomPrefixes=C,f.hasEvent=J,f.testProp=function(a){return B([a])},f.testAllProps=p,f.testStyles=A,v.className=v.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+G.join(" ")),f}(this,this.document);
(function(g,d,y){function u(b){return"[object Function]"==z.call(b)}function B(b){return"string"==typeof b}function p(){}function O(b){return!b||"loaded"==b||"complete"==b||"uninitialized"==b}function f(){var b=C.shift();D=1;b?b.t?w(function(){("c"==b.t?a.injectCss:a.injectJs)(b.s,0,b.a,b.x,b.e,1)},0):(b(),f()):D=0}function v(b,c,s,k,g,m,l){function r(a){if(!t&&O(n.readyState)&&(L.r=t=1,!D&&f(),n.onload=n.onreadystatechange=null,a)){"img"!=b&&w(function(){G.removeChild(n)},50);for(var d in q[c])q[c].hasOwnProperty(d)&&
q[c][d].onload()}}l=l||a.errorTimeout;var n=d.createElement(b),t=0,p=0,L={t:s,s:c,e:g,a:m,x:l};1===q[c]&&(p=1,q[c]=[]);"object"==b?n.data=c:(n.src=c,n.type=b);n.width=n.height="0";n.onerror=n.onload=n.onreadystatechange=function(){r.call(this,p)};C.splice(k,0,L);"img"!=b&&(p||2===q[c]?(G.insertBefore(n,E?null:x),w(r,l)):q[c].push(n))}function c(b,a,c,d,k){return D=0,a=a||"j",B(b)?v("c"==a?I:H,b,a,this.i++,c,d,k):(C.splice(this.i++,0,b),1==C.length&&f()),this}function m(){var b=a;return b.loader={load:c,
i:0},b}var k=d.documentElement,w=g.setTimeout,x=d.getElementsByTagName("script")[0],z={}.toString,C=[],D=0,N="MozAppearance"in k.style,E=N&&!!d.createRange().compareNode,G=E?k:x.parentNode,k=g.opera&&"[object Opera]"==z.call(g.opera),k=!!d.attachEvent&&!k,H=N?"object":k?"script":"img",I=k?"script":H,A=Array.isArray||function(b){return"[object Array]"==z.call(b)},J=[],q={},F={timeout:function(b,a){return a.length&&(b.timeout=a[0]),b}},K,a;a=function(b){function c(b){b=b.split("!");var a=J.length,d=
b.pop(),e=b.length,d={url:d,origUrl:d,prefixes:b},f,h,g;for(h=0;h<e;h++)g=b[h].split("="),(f=F[g.shift()])&&(d=f(d,g));for(h=0;h<a;h++)d=J[h](d);return d}function d(b,a,f,g,k){var h=c(b),l=h.autoCallback;h.url.split(".").pop().split("?").shift();h.bypass||(a&&(a=u(a)?a:a[b]||a[g]||a[b.split("/").pop().split("?")[0]]),h.instead?h.instead(b,a,f,g,k):(q[h.url]?h.noexec=!0:q[h.url]=1,f.load(h.url,h.forceCSS||!h.forceJS&&"css"==h.url.split(".").pop().split("?").shift()?"c":y,h.noexec,h.attrs,h.timeout),
(u(a)||u(l))&&f.load(function(){m();a&&a(h.origUrl,k,g);l&&l(h.origUrl,k,g);q[h.url]=2})))}function f(a,b){function c(a,f){if(a)if(B(a))f||(h=function(){var a=[].slice.call(arguments);k.apply(this,a);l()}),d(a,h,b,0,e);else{if(Object(a)===a)for(q in m=function(){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}(),a)a.hasOwnProperty(q)&&(!f&&!--m&&(u(h)?h=function(){var a=[].slice.call(arguments);k.apply(this,a);l()}:h[q]=function(a){return function(){var b=[].slice.call(arguments);a&&a.apply(this,
b);l()}}(k[q])),d(a[q],h,b,q,e))}else!f&&l()}var e=!!a.test,g=a.load||a.both,h=a.callback||p,k=h,l=a.complete||p,m,q;c(e?a.yep:a.nope,!!g);g&&c(g)}var k,g,l=this.yepnope.loader;if(B(b))d(b,0,l,0);else if(A(b))for(k=0;k<b.length;k++)g=b[k],B(g)?d(g,0,l,0):A(g)?a(g):Object(g)===g&&f(g,l);else Object(b)===b&&f(b,l)};a.addPrefix=function(a,c){F[a]=c};a.addFilter=function(a){J.push(a)};a.errorTimeout=1E4;null==d.readyState&&d.addEventListener&&(d.readyState="loading",d.addEventListener("DOMContentLoaded",
K=function(){d.removeEventListener("DOMContentLoaded",K,0);d.readyState="complete"},0));g.yepnope=m();g.yepnope.executeStack=f;g.yepnope.injectJs=function(b,c,g,k,m,q){var l=d.createElement("script"),r,n;k=k||a.errorTimeout;l.src=b;for(n in g)l.setAttribute(n,g[n]);c=q?f:c||p;l.onreadystatechange=l.onload=function(){!r&&O(l.readyState)&&(r=1,c(),l.onload=l.onreadystatechange=null)};w(function(){r||(r=1,c(1))},k);m?l.onload():x.parentNode.insertBefore(l,x)};g.yepnope.injectCss=function(a,c,g,k,m,q){k=
d.createElement("link");var l;c=q?f:c||p;k.href=a;k.rel="stylesheet";k.type="text/css";for(l in g)k.setAttribute(l,g[l]);m||(x.parentNode.insertBefore(k,x),w(c,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};
//]]>
